version: 1.1.0.{build}

configuration: Release

image: Visual Studio 2017

environment:
  packageVersion: 1.1.0

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(packageVersion)'

before_build:
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true

cache:
  - packages -> **\packages.config 

deploy:
  provider: NuGet
  api_key:
    secure: Wez33pNFdKSfZiJUnZhhLpmQbgmchJupLyAg2fVFc5k9BC10TcEsPMij4MdTLMoB
  on:
    branch: master
    appveyor_repo_tag: true