version: 1.0.1.{build}

configuration: Release

environment:
  packageVersion: 1.0.1

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(packageVersion)'

before_build:
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true

cache:
  - packages -> **\packages.config 

deploy:
  provider: NuGet
  api_key:
    secure: Kpo2YYLP/rdpADh2H4iFiL5KVciwSu8j5znuL47rK8XrnycbNxln0f92Bw5x2tBC
  on:
    branch: master
    appveyor_repo_tag: true